<?php
/**
 * Fires only on "Delete" from the Plugins screen, never on deactivation.
 * Data removal is opt-in via Settings -> "Remove all data on uninstall" -
 * mirrors the checkbox-gated pattern used by the sibling shuttle-booking
 * plugin, but this one actually drops every table it created.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

$ybs_settings = get_option( 'ybs_settings', array() );

if ( empty( $ybs_settings['remove_data_on_uninstall'] ) ) {
	return;
}

global $wpdb;

/*
 * This file runs only while WordPress is deleting the plugin. Every query
 * below is a deliberate direct call against either core taxonomy tables or
 * the plugin's own custom tables: there is nothing worth caching because the
 * data is being destroyed, and dropping the tables the migrator created is
 * the whole point of the file.
 */
// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange

// Scheduled events.
wp_clear_scheduled_hook( 'ybs_daily_maintenance' );

// Yachts and their postmeta/terms relationships.
$yacht_ids = get_posts(
	array(
		'post_type'   => 'yacht',
		'post_status' => 'any',
		'numberposts' => -1,
		'fields'      => 'ids',
	)
);

foreach ( $yacht_ids as $yacht_id ) {
	wp_delete_post( $yacht_id, true );
}

// Taxonomy terms (registered on `init`, which uninstall.php never fires, so
// term_taxonomy rows are removed directly rather than via the term API).
foreach ( array( 'yacht_class', 'yacht_occasion' ) as $taxonomy ) {
	$rows = $wpdb->get_results(
		$wpdb->prepare( "SELECT term_id, term_taxonomy_id FROM {$wpdb->term_taxonomy} WHERE taxonomy = %s", $taxonomy )
	);

	if ( ! $rows ) {
		continue;
	}

	$term_ids          = wp_list_pluck( $rows, 'term_id' );
	$term_taxonomy_ids = wp_list_pluck( $rows, 'term_taxonomy_id' );

	// The only interpolated part of each query below is a run of "%d"
	// placeholders generated by array_fill() from the row count, so the real
	// values still go through $wpdb->prepare(). The sniffs cannot see
	// placeholders that were built at runtime, hence the annotations.
	$tt_placeholders = implode( ',', array_fill( 0, count( $term_taxonomy_ids ), '%d' ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->term_relationships} WHERE term_taxonomy_id IN ({$tt_placeholders})", $term_taxonomy_ids ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->term_taxonomy} WHERE term_taxonomy_id IN ({$tt_placeholders})", $term_taxonomy_ids ) );

	// Only this taxonomy's own terms, and only those left with no remaining
	// taxonomy row - a shared term still used elsewhere must survive.
	$term_placeholders = implode( ',', array_fill( 0, count( $term_ids ), '%d' ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->terms} WHERE term_id IN ({$term_placeholders}) AND term_id NOT IN ( SELECT term_id FROM {$wpdb->term_taxonomy} )", $term_ids ) );
}

// Custom tables - every one the migrator creates.
$tables = array(
	'ybs_bookings',
	'ybs_guests',
	'ybs_pricing_rules',
	'ybs_addons',
	'ybs_yacht_addons',
	'ybs_booking_addons',
	'ybs_email_templates',
	'ybs_email_logs',
	'ybs_newsletter_subscribers',
);

foreach ( $tables as $table ) {
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name comes from the hardcoded list above; prepare() cannot parameterise an identifier.
	$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}{$table}" );
}

// Options.
$options = array(
	'ybs_settings',
	'ybs_db_version',
	'ybs_flush_rewrite_rules',
	'ybs_yacht_class_terms_seeded',
	'ybs_yacht_occasion_terms_seeded',
);

foreach ( $options as $option ) {
	delete_option( $option );
}

$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->options} WHERE option_name LIKE %s", $wpdb->esc_like( 'ybs_' ) . '%' ) );

// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange

// Roles/capabilities.
require_once __DIR__ . '/includes/Capabilities.php';
\Ybs\Capabilities::uninstall();
