<?php
/**
 * Fires only on "Delete" from the Plugins screen, never on deactivation.
 * Data removal is opt-in via Settings -> "Remove all data on uninstall" -
 * mirrors the checkbox-gated pattern used by the sibling shuttle-booking
 * plugin, but this one actually drops every table it created.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

$mageyabo_settings = get_option( 'mageyabo_settings', array() );

if ( empty( $mageyabo_settings['remove_data_on_uninstall'] ) ) {
	return;
}

global $wpdb;

/*
 * This file runs only while WordPress is deleting the plugin. Every query
 * below is a deliberate direct call against either core taxonomy tables or
 * the plugin's own custom tables: there is nothing worth caching because the
 * data is being destroyed, and dropping the tables the migrator created is
 * the whole point of the file.
 */
// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange, PluginCheck.Security.DirectDB.UnescapedDBParameter

// Scheduled events.
wp_clear_scheduled_hook( 'mageyabo_daily_maintenance' );

// Yachts and their postmeta/terms relationships.
$mageyabo_yacht_ids = get_posts(
	array(
		'post_type'   => 'mageyabo_yacht',
		'post_status' => 'any',
		'numberposts' => -1,
		'fields'      => 'ids',
	)
);

foreach ( $mageyabo_yacht_ids as $mageyabo_yacht_id ) {
	wp_delete_post( $mageyabo_yacht_id, true );
}

// Taxonomy terms (registered on `init`, which uninstall.php never fires, so
// term_taxonomy rows are removed directly rather than via the term API).
foreach ( array( 'mageyabo_yacht_class', 'mageyabo_yacht_occasion' ) as $taxonomy ) {
	$mageyabo_rows = $wpdb->get_results(
		$wpdb->prepare( "SELECT term_id, term_taxonomy_id FROM {$wpdb->term_taxonomy} WHERE taxonomy = %s", $taxonomy )
	);

	if ( ! $mageyabo_rows ) {
		continue;
	}

	$mageyabo_term_ids          = wp_list_pluck( $mageyabo_rows, 'term_id' );
	$mageyabo_term_taxonomy_ids = wp_list_pluck( $mageyabo_rows, 'term_taxonomy_id' );

	// The only interpolated part of each query below is a run of "%d"
	// placeholders generated by array_fill() from the row count, so the real
	// values still go through $wpdb->prepare(). The sniffs cannot see
	// placeholders that were built at runtime, hence the annotations.
	$mageyabo_tt_placeholders = implode( ',', array_fill( 0, count( $mageyabo_term_taxonomy_ids ), '%d' ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->term_relationships} WHERE term_taxonomy_id IN ({$mageyabo_tt_placeholders})", $mageyabo_term_taxonomy_ids ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->term_taxonomy} WHERE term_taxonomy_id IN ({$mageyabo_tt_placeholders})", $mageyabo_term_taxonomy_ids ) );

	// Only this taxonomy's own terms, and only those left with no remaining
	// taxonomy row - a shared term still used elsewhere must survive.
	$mageyabo_term_placeholders = implode( ',', array_fill( 0, count( $mageyabo_term_ids ), '%d' ) );
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- interpolated value is a generated "%d,%d,..." placeholder list.
	$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->terms} WHERE term_id IN ({$mageyabo_term_placeholders}) AND term_id NOT IN ( SELECT term_id FROM {$wpdb->term_taxonomy} )", $mageyabo_term_ids ) );
}

// Custom tables - every one the migrator creates.
$mageyabo_tables = array(
	'mageyabo_bookings',
	'mageyabo_guests',
	'mageyabo_pricing_rules',
	'mageyabo_addons',
	'mageyabo_yacht_addons',
	'mageyabo_booking_addons',
	'mageyabo_newsletter_subscribers',
);

// Tables belonging to add-ons are deliberately not listed: each add-on drops
// its own on its own uninstall. Dropping them from here would destroy a site's
// coupons and mail history the moment this plugin was removed, even with the
// add-on still installed.

foreach ( $mageyabo_tables as $mageyabo_table ) {
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name comes from the hardcoded list above; prepare() cannot parameterise an identifier.
	$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}{$mageyabo_table}" );
}

// Options.
$mageyabo_options = array(
	'mageyabo_settings',
	'mageyabo_db_version',
	'mageyabo_flush_rewrite_rules',
	'mageyabo_yacht_class_terms_seeded',
	'mageyabo_yacht_occasion_terms_seeded',
);

foreach ( $mageyabo_options as $mageyabo_option ) {
	delete_option( $mageyabo_option );
}

$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->options} WHERE option_name LIKE %s", $wpdb->esc_like( 'mageyabo_' ) . '%' ) );

// phpcs:enable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange, PluginCheck.Security.DirectDB.UnescapedDBParameter

// Roles/capabilities.
require_once __DIR__ . '/includes/Capabilities.php';
\MageYaBo\Capabilities::uninstall();
